/**
 * Type definitions for game content rewriting system
 */

/**
 * Game record from CSV file
 */
export interface GameRecord {
  title: string;
  pageUrl: string;
  gameUrl: string;
  coverImage: string;
  rating: string;
  contentPath: string;
  metaTitle?: string; // To be generated
  metaDescription?: string; // To be generated
  categories?: string; // Comma-separated string from CSV
  tags?: string; // Comma-separated string from CSV
}

/**
 * Game content structure (generated by AI)
 */
export interface GameContent {
  shortDescription: string;
  whatIs: string;
  howToPlay: string;
  whatMakesSpecial: string;
  faqs: FAQ[];
  metaTitle?: string;
  metaDescription?: string;
}

/**
 * FAQ structure
 */
export interface FAQ {
  question: string;
  answer: string;
}

/**
 * Result of processing a single game
 */
export interface RewriteResult {
  success: boolean;
  game: GameRecord;
  content?: GameContent;
  error?: string;
  attempts: number;
}

/**
 * Game metadata for JSON export
 * Note: Full content stored in separate markdown files (referenced by contentPath)
 */
export interface GameDataExport {
  title: string;
  pageUrl: string;
  gameUrl: string;
  coverImage: string;
  rating: string;
  contentPath: string;
  metaTitle: string;
  metaDescription: string;
  categories?: string[];
  tags?: string[];
}

/**
 * Run mode: test (first 5 games) or production (all games)
 */
export type RunMode = 'test' | 'production';

/**
 * Current CSV file processing progress
 */
export interface CsvFileProgress {
  totalGames: number;
  processedGames: number;
  successCount: number;
  failedGames: string[];
  lastProcessedIndex: number;
}

/**
 * Global processing progress (all CSV files)
 */
export interface GlobalProgress {
  mode: RunMode;
  currentCsvFile: string;
  currentCsvIndex: number;
  totalCsvFiles: number;
  allCsvFiles: string[]; // All CSV files to process
  processedCsvFiles: string[]; // Successfully completed CSV files
  currentFileProgress: CsvFileProgress;
  timestamp: string;
}

/**
 * @deprecated Use GlobalProgress instead
 * Processing progress for resume capability (legacy, for single CSV file)
 */
export interface ProcessingProgress {
  csvFile: string;
  totalGames: number;
  processedGames: number;
  successCount: number;
  failedGames: string[];
  lastProcessedIndex: number;
  timestamp: string;
}
